openapi: 3.0.0
info:
  description: This is detailed rest api document for CMA mobile project. It must be followed by both (backend and frontend) developers to match the highest quality of the work.
    Author - Nishant Shah
  version: 1.0.0
  title: CMA API specification 
  contact:
    name: Saleh Alhashmi
    email: saleh.alhashmi@cma.gov.om
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Device
    description: Operations about device specific
  - name: Insurance
    description: Operations about insurance complaint
  - name: News-Events
    description: Operations about news and events 
  - name: Hall
    description: Operations about hall service.
  - name: Wishtleblower
    description: Operations about wishtleblower service.
paths:
  /news:
    get:
      tags:
        - News-Events
      summary: To get access token for user's device
      description: This can only be done by the any user.
      operationId: sendNews
      parameters:
        - in: query
          name: page
          description: Page number 
          required: true
          schema:
            type: integer
        - in: query
          name: limit
          description: items per page
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/News"
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "401":
          description: unauthorized - token expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - jwt: []
  /events:
    get:
      tags:
        - News-Events
      summary: To get access token for user's device
      description: This can only be done by the any user.
      operationId: sendEvent
      parameters:
        - in: query
          name: page
          description: Page number 
          required: true
          schema:
            type: integer
        - in: query
          name: limit
          description: items per page
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "401":
          description: unauthorized - token expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - jwt: []
        
  /access_token:
    get:
      tags:
        - Device
      summary: To get access token for user's device
      description: This can only be done by the any user.
      operationId: sendToken
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /push:
    post:
      tags:
        - Device
      summary: Add user's push token
      description: This can only be done by the logged in user.
      operationId: addPushToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PushNotification"
        description: Created user object
        required: true
      responses:
        "201":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "401":
          description: unauthorized - token expired
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - jwt: []
 
  /insurance/complaint:
    post:
      tags:
        - Insurance
      summary: Add user's insurance complaint
      description: This can only be done by the logged in user.
      operationId: createInsuranceComplaint
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Insurance_Complaint"
        description: Created insurance complaint object
        required: true
      responses:
        "201":
          description: created successfully.
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "401":
          description: unauthorized - token expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - jwt: []
  /insurance/complaint/:
    get:
      deprecated: true
      tags:
        - Insurance
      summary: Gives all insurance complaints. 
      responses:
        "417":
          description: service not avialable
      security:
        - jwt: []
  /insurance/complaint/{complaint_id}:
    get:
      tags:
        - Insurance
      summary: See the status of insurance complaint.
      description: This can only be done by the tokened in user.
      operationId: statusInsuranceComplaint
      parameters:
        - in: path
          name: complaint_id
          description: Created user object
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Insurance_Complaint"
        "401":
          description: unauthorized - token expired
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Too many request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - jwt: []
externalDocs:
  description: Find out more about CMA
  url: https://www.cma.gov.om/
servers:
  - url: https://localhost/v1
  - url: http://localhost/v1
components:
  securitySchemes:
    jwt:
      type: apiKey
      name: jwt_token
      in: header
  schemas:
    Insurance_Complaint:
      type: object
      required:
        - insurance_company
        - user
      properties:
        insurance_company:
          $ref: "#/components/schemas/Insurance_Company"
        claim_number:
          type: string
        policy_number:
          type: string
        insurance_type:
          type: string
          enum:
            - Car Insurance
            - Health Insurance
            - Life Insurance
            - Travel Insurance
            - Property Insurance
        insurance_complaint_type:
          type: string
        status:
          type: string
          enum:
            - deleted
            - approved
            - rejected
            - incomplete
            - processing
        details:
          type: string
        documents:
          type: array
          items:
            type: string
            format: binary
            description: File
        user:
          $ref: "#/components/schemas/User"
    User:
      type: object
      required:
        - id
        - mobile
        - email
        - id_card_copy
        - nationality
        - name
      properties:
        id:
          type: string
        picture:
          type: string
          format: binary
        name:
          type: string
        email:
          type: string
          format: email
        nationality:
          type: string
        mobile:
          type: string
          format: phone
        id_card_copy:
          type: string
          format: binary
    Insurance_Company:
      type: object
      properties:
        company_name:
          type: string
        company_id:
          type: string
    PushNotification:
      type: object
      properties:
        mobile:
          type: string
          format: phone
        push_token:
          type: string
        os:
          type: string
          enum:
            - android
            - iOS
        device_info:
          type: string
          
    Token:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
    News:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        image:
          type: string
          format: url
        publish_date:
          type: string
          format: date-time
    
    Event:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        venue:
          type: string
          format: address
        image:
          type: string
          format: url
        event_date:
          type: string
          format: date
        event_time:
          type: string
          format: date-time
        
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        exception:
          type: string
        message:
          type: string
        host:
          type: string
        endpoint:
          type: string
